version: "3.4"
services:
  quiz-node-rest-api-prod:
    image: quiz-node-prod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_PORT: $APP_PORT
    ports:
      - 9500:9500
  # sqlite3:
  #   image: nouchka/sqlite3:latest
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./db/:/root/db/