FROM node:14-alpine as local-dev-node

WORKDIR /home/node
COPY ./package* ./swagger.json ./

RUN npm i
COPY ./tsconfig.json ./
COPY ./src ./src

ARG APP_PORT
ENV APP_PORT=$APP_PORT
EXPOSE 9500 $APP_PORT
CMD [ "npm", "run", "dev" ]
